# Generated by Django 5.2.3 on 2025-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigin_f', models.BigIntegerField()),
                ('bool_f', models.BooleanField()),
                ('data_f', models.DateField(auto_now_add=True)),
                ('char_f', models.CharField(max_length=255)),
                ('decimal_f', models.DecimalField(decimal_places=2, max_digits=10)),
                ('float_f', models.FloatField()),
                ('int_f', models.IntegerField(default=100)),
                ('text_f', models.TextField()),
            ],
        ),
    ]
