# Generated by Django 5.2.3 on 2025-08-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_newtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('S', 'Smallxxx'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('qty', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
